### ISSUE TITLE
SSL_ERROR_RX_MALFORMED_CERTIFICATE with Let's Encrypt certificates

### ISSUE THREAD

**Issue by ghost** [jedisct1/doh-server#48]
I'm using the version installed from crates. When I try to use Let's Encrypt cert/key it doesn't work:

```
doh-proxy --listen-address 127.0.0.1:3001 --tls-cert-key-path privkey.pem --tls-cert-path fullchain.pem
```

I get a `SSL_ERROR_RX_MALFORMED_CERTIFICATE` error in the browser and a `* error:1416F09F:SSL routines:tls_process_server_certificate:length mismatch` error via curl. It does work when I use the self-signed certificate provided. Maybe rustls doesn't like the format used by Let's Encrypt?

**Comment by kcortman** [comment]
Ghost,

I'm clearly late to the party, but I found your post and too ran into the same issue: 

Try this:  append your .crt file with the .key file (e.g. cat localhost.key >> localhost.crt) and try just using the '-I ~/.../localhost.crt' option and restart your service.  

Best,
KO
