### ISSUE TITLE
Cannot download binaries if not logged into Github

### ISSUE THREAD

**Issue by vsviridov** [jedisct1/doh-server#49]
Makes it difficult to do via SSH on a remote server

**Comment by jedisct1** [comment]
Do you think you could submit a PR with the required changes to the GitHub actions to address this? That would be great!

Thanks!

**Comment by vsviridov** [comment]
I have not worked with GH Actions yet, unfortunately, but a quick search points out the possibility of creating a Release from within an action, and releases do have artifacts, and those are public for everyone...

**Comment by jedisct1** [comment]
I don't have much experience with GH actions either.

But you can always use [piknik](https://github.com/jedisct1/piknik) to transfer files between machines :)

**Comment by outloudvi** [comment]
Hi, Actions' artifacts [expire automatically after 90 days](https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts#downloading-and-deleting-artifacts-after-a-workflow-run-is-complete), and as a result the artifact links stop working again. An alternative would be publishing binaries directly to the releases (using [actions/upload-release-asset](https://github.com/actions/upload-release-asset)). How do you think of this idea?
