### ISSUE TITLE
HTTPS/SSL with self signed failed

### ISSUE THREAD

**Issue by idanless** [jedisct1/doh-server#50]
Hi
i try make test with self signed (pem format) 
**./doh-proxy  -l 10.100.102.20:3000 -u 127.0.0.1:53 --tls-cert-path server.pem (your pem)**
and this continue be on http:
**print "Listening on http://10.100.102.20:3000/dns-query"**
what i doing  wrong ?

**Comment by jedisct1** [comment]
You also need to provide the cert key with `--tls-cert-key-path` (which can be the same file as the other one).

Please note that `dnscrypt-proxy` requires certificates to be signed by a known CA.

If you are using your own CA, it should be added to the `[doh_client_x509_auth]` section:

```toml
#################################################################
#        Certificate-based client authentication for DoH        #
#################################################################

# Use a X509 certificate to authenticate yourself when connecting to DoH servers.
# This is only useful if you are operating your own, private DoH server(s).
# 'creds' maps servers to certificates, and supports multiple entries.
# If you are not using the standard root CA, an optional "root_ca"
# property set to the path to a root CRT file can be added to a server entry.

[doh_client_x509_auth]

#
# creds = [
#    { server_name='myserver', client_cert='client.crt', client_key='client.key' }
# ]
```

**Comment by idanless** [comment]
first tnx for the quick answer 
were i need to configure this ?
i run it from "cargo install doh-proxy" and i have bin
 do i need compiler it from the  source ? (btw i don't found "dnscrypt-proxy" in the system)

**Comment by jedisct1** [comment]
This is a command-line option. See the documentation: https://github.com/jedisct1/doh-server#http2-termination
