### ISSUE TITLE
HTTP/2 Termination Question

### ISSUE THREAD

**Issue by ianbashford** [jedisct1/doh-server#55]
Hey,
I've configured doh-server to run behind encrypted-dns-server.  Both are running in docker containers.  The dnscrypt service is based on dnscrypt-server-docker.  

I've directed dnscrypt-proxy (static configuration).  Unexpectedly I saw warnings around HTTP/2
```
[2021-01-03 11:48:08] [WARNING] [dohdo] does not support HTTP/2
[2021-01-03 11:48:08] [NOTICE] [dohdo] OK (DoH) - rtt: 8ms
[2021-01-03 11:48:08] [WARNING] [dohv] does not support HTTP/2
[2021-01-03 11:48:08] [NOTICE] [dohv] OK (DoH) - rtt: 6ms
```

Did I misunderstand https://github.com/jedisct1/doh-server#accepting-both-dnscrypt-and-doh-connections-on-port-443 or should that support HTTP/2?

**Comment by jedisct1** [comment]
Hi Ian,

I think HTTP/2 support `doh-server` was unintentionally disabled after a dependency update (`hyper`, that has breaking changes all the time).

I'm going to look at this right now.

**Comment by ianbashford** [comment]
Thanks Frank,

Not my specific area of expertise but if I can help with anything including testing then let me know

Ian

**Comment by jedisct1** [comment]
In spite of the HTTP/2 issue, does everything work as expected?

**Comment by ianbashford** [comment]
Yes -- I've got IPv4 up and working on both servers and I'm checking they're bedded in. Response time seemed good despite lack of HTTP/2.

I'm just setting up IPv6 now [ I don't have native IPv6 - just a VPN for testing ] so I should be in a position to update the public resolvers in a few days... 

FWIW, I saw a couple of closed issues related to using LetsEncrypt certificates - I had similar issues and resorted to cat'ing the private key and certs together into a single file to make it work. (https://github.com/jedisct1/doh-server/issues/48).  TBH I don't understand why it didn't work, or why this was a fix...
I'm happy to document the details, but I always hang back a bit while I don't understand why...

**Comment by jedisct1** [comment]
Hi Ian,

And sorry for addressing these so late.

Issues with the Let's Encrypt certificates have been solved. No need to concatenate files any more.

And the HTTP/2 termination issue has been solved as well (HTTP/2 was supported, but needed to be manually announced in ALPN).
