### ISSUE TITLE
try to listen on both ipv4 and ipv6

### ISSUE THREAD

**Issue by icebluey** [jedisct1/doh-server#58]
I tried:
doh-proxy -l "127.0.0.1:3000 ; [::1]:3000"
doh-proxy -l "127.0.0.1:3000 , [::1]:3000"
doh-proxy -l "127.0.0.1:3000" -l "[::1]:3000"

All of these did not work.

**Comment by jedisct1** [comment]
Only a single address is supported, but `[::]` is the standard way to represent all addresses, IPv4 and IPv6.

So you may try `[::]:3000`.

**Comment by icebluey** [comment]
Is there a way to listen on localhost in both IPv4 and IPv6, like dnscrypt-proxy we can set "listen_addresses = ['127.0.0.1:53', '[::1]:53']"

**Comment by jedisct1** [comment]
This has to be added to the code.

After seeing your message I spent 30 minutes on it and eventually gave up.

But if you know how to do it, your contribution would be welcome :)

It is very lightweight, so I would just run two instances (actually, this is what I do for `crypto.sx`).

**Comment by jedisct1** [comment]
If you're using `dnscrypt-proxy`, you can use [encrypted-dns](encrypted-dns-server) instead, it has many more features, and supports multiple addresses :)
